[mapelement_0]
graphic="mapfunction,0"
vis=^mapelement_vis_both
category=1049

[mapelement_1]
graphic="mapfunction,1"
vis=^mapelement_vis_both
category=1050

[mapelement_2]
graphic="mapfunction,2"
vis=^mapelement_vis_both
category=1052

[mapelement_3]
graphic="mapfunction,3"
vis=^mapelement_vis_both
category=1053

[mapelement_4]
graphic="mapfunction,4"
vis=^mapelement_vis_both
category=1054

[mapelement_5]
graphic="mapfunction,5"
vis=^mapelement_vis_both
category=1055

[mapelement_6]
text=The Node
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_7]
graphic="mapfunction,7"
vis=^mapelement_vis_both
category=1057

[mapelement_8]
graphic="mapfunction,8"
vis=^mapelement_vis_both
category=1058

[mapelement_9]
graphic="mapfunction,9"
vis=^mapelement_vis_both
category=1059

[mapelement_10]
graphic="mapfunction,10"
vis=^mapelement_vis_both
category=1060

[mapelement_11]
graphic="mapfunction,11"
vis=^mapelement_vis_both
category=1061

[mapelement_12]
graphic="mapfunction,12"
vis=^mapelement_vis_both
category=1062

[mapelement_13]
graphic="mapfunction,86"
vis=^mapelement_vis_both
mapfunction=no
op1=Open
name=Map
category=1062

[mapelement_14]
graphic="mapfunction,87"
mapfunction=no
op1=Open
name=Map
category=1063

[mapelement_15]
graphic="mapfunction,13"
vis=^mapelement_vis_both
category=1064

[mapelement_16]
graphic="mapfunction,14"
vis=^mapelement_vis_both
category=1065

[mapelement_17]
graphic="mapfunction,15"
vis=^mapelement_vis_both
category=1066

[mapelement_18]
graphic="mapfunction,16"
vis=^mapelement_vis_both
category=1067

[mapelement_19]
graphic="mapfunction,17"
vis=^mapelement_vis_both
category=1068

[mapelement_20]
graphic="mapfunction,18"
vis=^mapelement_vis_both
category=1069

[mapelement_21]
graphic="mapfunction,19"
vis=^mapelement_vis_both
category=1070

[mapelement_22]
graphic="mapfunction,20"
vis=^mapelement_vis_both
category=1071

[mapelement_23]
graphic="mapfunction,21"
vis=^mapelement_vis_both
category=1072

[mapelement_24]
graphic="mapfunction,22"
vis=^mapelement_vis_both
category=1073

[mapelement_25]
graphic="mapfunction,23"
vis=^mapelement_vis_both
category=1074

[mapelement_26]
graphic="mapfunction,24"
vis=^mapelement_vis_both
category=1075

[mapelement_27]
graphic="mapfunction,25"
vis=^mapelement_vis_both
category=1076

[mapelement_28]
graphic="mapfunction,26"
vis=^mapelement_vis_both
category=1077

[mapelement_29]
graphic="mapfunction,27"
vis=^mapelement_vis_both
category=1078

[mapelement_30]
graphic="mapfunction,28"
vis=^mapelement_vis_both
category=1079

[mapelement_31]
graphic="mapfunction,29"
vis=^mapelement_vis_both
category=1080

[mapelement_32]
graphic="mapfunction,30"
vis=^mapelement_vis_both
category=1081

[mapelement_33]
graphic="mapfunction,31"
vis=^mapelement_vis_both
category=1082

[mapelement_34]
graphic="mapfunction,32"
vis=^mapelement_vis_both
category=1083

[mapelement_35]
graphic="mapfunction,33"
vis=^mapelement_vis_both
category=1084

[mapelement_36]
graphic="mapfunction,34"
vis=^mapelement_vis_both
category=1085

[mapelement_37]
graphic="mapfunction,35"
vis=^mapelement_vis_both
category=1086

[mapelement_38]
graphic="mapfunction,36"
vis=^mapelement_vis_both
category=1081

[mapelement_39]
graphic="mapfunction,37"
vis=^mapelement_vis_both
category=1081

[mapelement_40]
graphic="mapfunction,38"
vis=^mapelement_vis_both
category=1087

[mapelement_41]
graphic="mapfunction,39"
vis=^mapelement_vis_both
category=1088

[mapelement_42]
graphic="mapfunction,40"
vis=^mapelement_vis_both
category=1089

[mapelement_43]
graphic="mapfunction,41"
vis=^mapelement_vis_both
category=1090

[mapelement_44]
graphic="mapfunction,42"
vis=^mapelement_vis_both
category=1091

[mapelement_45]
graphic="mapfunction,43"
vis=^mapelement_vis_both
category=1092

[mapelement_46]
graphic="mapfunction,44"
vis=^mapelement_vis_both
category=1093

[mapelement_47]
graphic="mapfunction,45"
vis=^mapelement_vis_both
category=1094

[mapelement_48]
graphic="mapfunction,46"
vis=^mapelement_vis_both
category=1095

[mapelement_49]
graphic="mapfunction,47"
vis=^mapelement_vis_both
category=1096

[mapelement_50]
graphic="mapfunction,48"
vis=^mapelement_vis_both
category=1097

[mapelement_51]
graphic="mapfunction,49"
vis=^mapelement_vis_both
category=1098

[mapelement_52]
graphic="mapfunction,50"
vis=^mapelement_vis_both
category=1081

[mapelement_53]
graphic="mapfunction,51"
vis=^mapelement_vis_both
category=1099

[mapelement_54]
graphic="mapfunction,52"
vis=^mapelement_vis_both
category=1100

[mapelement_55]
graphic="mapfunction,53"
vis=^mapelement_vis_both
category=1101

[mapelement_56]
graphic="mapfunction,54"
vis=^mapelement_vis_both
category=1102

[mapelement_57]
text=Weiss
colour=^white
mapfunction=no
category=1129

[mapelement_58]
graphic="mapfunction,56"
vis=^mapelement_vis_both
category=1104

[mapelement_59]
graphic="mapfunction,57"
vis=^mapelement_vis_both
category=1105

[mapelement_60]
graphic="mapfunction,58"
vis=^mapelement_vis_both
category=1106

[mapelement_61]
graphic="mapfunction,59"
vis=^mapelement_vis_both
category=1107

[mapelement_62]
graphic="mapfunction,60"
vis=^mapelement_vis_both
category=1108

[mapelement_63]
graphic="mapfunction,61"
vis=^mapelement_vis_both
category=1109

[mapelement_64]
graphic="mapfunction,62"
vis=^mapelement_vis_both
category=1110

[mapelement_65]
graphic="mapfunction,63"
vis=^mapelement_vis_both
category=1111

[mapelement_66]
graphic="mapfunction,64"
vis=^mapelement_vis_both
category=1112

[mapelement_67]
graphic="mapfunction,65"
vis=^mapelement_vis_both
category=1113

[mapelement_68]
graphic="mapfunction,67"
vis=^mapelement_vis_both
category=1114

[mapelement_69]
graphic="mapfunction,68"
vis=^mapelement_vis_both
category=1115

[mapelement_70]
graphic="mapfunction,69"
vis=^mapelement_vis_both
category=1116

[mapelement_71]
graphic="mapfunction,70"
vis=^mapelement_vis_both
category=1117

[mapelement_72]
graphic="mapfunction,71"
vis=^mapelement_vis_both
category=1118

[mapelement_73]
graphic="mapfunction,72"
vis=^mapelement_vis_both
category=1119

[mapelement_74]
graphic="mapfunction,73"
vis=^mapelement_vis_both
category=1120

[mapelement_75]
graphic="mapfunction,74"
vis=^mapelement_vis_both
category=1121

[mapelement_76]
graphic="mapfunction,75"
vis=^mapelement_vis_both
category=1122

[mapelement_77]
graphic="mapfunction,76"
vis=^mapelement_vis_both
category=1123

[mapelement_78]
text=Salt Mine
colour=^white
mapfunction=no
category=1129

[mapelement_79]
graphic="mapfunction,78"
vis=^mapelement_vis_both
category=1125

[mapelement_80]
graphic="mapfunction,79"
vis=^mapelement_vis_both
category=1125

[mapelement_81]
graphic="mapfunction,80"
vis=^mapelement_vis_both
category=1125

[mapelement_82]
graphic="mapfunction,81"
vis=^mapelement_vis_both
category=1125

[mapelement_83]
graphic="mapfunction,82"
vis=^mapelement_vis_both
category=1125

[mapelement_84]
graphic="mapfunction,83"
vis=^mapelement_vis_both
category=1126

[mapelement_85]
graphic="mapfunction,84"
vis=^mapelement_vis_both
category=1127

[mapelement_86]
graphic="mapfunction,85"
vis=^mapelement_vis_both
category=1128

[mapelement_87]
text=Lumbridge
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_88]
text=Varrock
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_89]
text=Kingdom of<br>Misthalin
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_90]
text=Al Kharid
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_91]
text=Duel<br>Arena
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_92]
text=Shantay<br>Pass
colour=^white
mapfunction=no
category=1129

[mapelement_93]
text=Toll<br>Gate
colour=^white
mapfunction=no
category=1129

[mapelement_94]
text=Tutorial Island
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_95]
text=Port<br>Sarim
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_96]
text=Falador
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_97]
text=Edgeville
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_98]
text=Brimhaven
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_99]
text=Karamja
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_100]
text=Crandor
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_101]
text=Entrana
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_102]
text=Draynor<br>Village
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_103]
text=Jail
colour=^white
mapfunction=no
category=1129

[mapelement_104]
text=Market
colour=^white
mapfunction=no
category=1129

[mapelement_105]
text=Draynor Manor
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_106]
text=Barbarian<br>Village
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_107]
text=Desert Mining<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_108]
text=Bedabin<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_109]
text=Exam Centre
colour=^white
mapfunction=no
category=1129

[mapelement_110]
text=Digsite
colour=^white
mapfunction=no
category=1129

[mapelement_111]
text=Lumber Yard
colour=^white
mapfunction=no
category=1129

[mapelement_112]
text=Palace
colour=^white
mapfunction=no
category=1129

[mapelement_113]
text=Grand Exchange
colour=^white
mapfunction=no
category=1129

[mapelement_114]
text=Cooks'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_115]
text=Monastery
colour=^white
mapfunction=no
category=1129

[mapelement_116]
text=Dwarven<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_117]
text=Ice<br>Mountain
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_118]
text=Black Knights'<br>Fortress
colour=^white
mapfunction=no
category=1129

[mapelement_119]
text=Goblin<br>Village
colour=^white
mapfunction=no
category=1129

[mapelement_120]
text=White Knights'<br>Castle
colour=^white
mapfunction=no
category=1129

[mapelement_121]
text=Park
colour=^white
mapfunction=no
category=1129

[mapelement_122]
text=Kingdom of<br>Asgarnia
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_123]
text=Dark Wizards'<br>Tower
colour=^white
mapfunction=no
category=1129

[mapelement_124]
text=Slayer<br>Tower
colour=^white
mapfunction=no
category=1129

[mapelement_125]
text=Melzar's<br>Maze
colour=^white
mapfunction=no
category=1129

[mapelement_126]
text=Rimmington
colour=^white
mapfunction=no
category=1129

[mapelement_127]
text=Wizards' Tower
colour=^white
mapfunction=no
category=1129

[mapelement_128]
text=Lumbridge<br>Swamp
colour=^white
mapfunction=no
category=1129

[mapelement_129]
text=Fishing<br>Platform
colour=^white
mapfunction=no
category=1129

[mapelement_130]
text=Tai Bwo Wannai
colour=^white
mapfunction=no
category=1129

[mapelement_131]
text=Shilo Village
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_132]
text=Ship Yard
colour=^white
mapfunction=no
category=1129

[mapelement_133]
text=Cairn Isle
colour=^white
mapfunction=no
category=1129

[mapelement_134]
text=Kharazi Jungle
colour=^white
mapfunction=no
category=1129

[mapelement_135]
text=Chaos<br>Temple
colour=^white
mapfunction=no
category=1129

[mapelement_136]
text=Graveyard of<br>Shadows
colour=^white
mapfunction=no
category=1129

[mapelement_137]
text=Bandit<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_138]
text=Dark Warriors'<br>Fortress
colour=^white
mapfunction=no
category=1129

[mapelement_139]
text=Ruins
colour=^white
mapfunction=no
category=1129

[mapelement_140]
text=The Forgotten<br>Cemetery
colour=^white
mapfunction=no
category=1129

[mapelement_141]
text=Bone Yard
colour=^white
mapfunction=no
category=1129

[mapelement_142]
text=Lava Dragon<br>Isle
colour=^white
mapfunction=no
category=1129

[mapelement_143]
text=Wilderness
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_144]
text=Lava Maze
colour=^white
mapfunction=no
category=1129

[mapelement_145]
text=Frozen Waste<br>Plateau
colour=^white
mapfunction=no
category=1129

[mapelement_146]
text=Agility Training<br>Area
colour=^white
mapfunction=no
category=1129

[mapelement_147]
text=Pirates'<br>Hideout
colour=^white
mapfunction=no
category=1129

[mapelement_148]
text=Mage Arena
colour=^white
mapfunction=no
category=1129

[mapelement_149]
text=Deserted<br>Keep
colour=^white
mapfunction=no
category=1129

[mapelement_150]
text=Resource Area
colour=^white
mapfunction=no
category=1129

[mapelement_151]
text=Scorpion<br>Pit
colour=^white
mapfunction=no
category=1129

[mapelement_152]
text=Rogues' Castle
colour=^white
mapfunction=no
category=1129

[mapelement_153]
text=Demonic<br>Ruins
colour=^white
mapfunction=no
category=1129

[mapelement_154]
text=Fountain<br>of Rune
colour=^white
mapfunction=no
category=1129

[mapelement_155]
text=Bear
colour=^white
mapfunction=no
category=1129

[mapelement_156]
text=Spider
colour=^white
mapfunction=no
category=1129

[mapelement_157]
text=Heroes'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_158]
text=Druids'<br>Circle
colour=^white
mapfunction=no
category=1129

[mapelement_159]
text=Taverley
colour=^white
mapfunction=no
category=1129

[mapelement_160]
text=White Wolf<br>Mountain
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_161]
text=Catherby
colour=^white
mapfunction=no
category=1129

[mapelement_162]
text=Camelot<br>Castle
colour=^white
mapfunction=no
category=1129

[mapelement_163]
text=Seers'<br>Village
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_164]
text=Sinclair Mansion
colour=^white
mapfunction=no
category=1129

[mapelement_165]
text=Flax
colour=^white
mapfunction=no
category=1129

[mapelement_166]
text=Beehives
colour=^white
mapfunction=no
category=1129

[mapelement_167]
text=Sorcerer's Tower
colour=^white
mapfunction=no
category=1129

[mapelement_168]
text=Keep<br>Le Faye
colour=^white
mapfunction=no
category=1129

[mapelement_169]
text=Legends'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_170]
text=Hemenster
colour=^white
mapfunction=no
category=1129

[mapelement_171]
text=McGrubor's<br>Wood
colour=^white
mapfunction=no
category=1129

[mapelement_172]
text=Coal<br>Trucks
colour=^white
mapfunction=no
category=1129

[mapelement_173]
text=Fishing<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_174]
text=Kingdom of<br>Kandarin
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_175]
text=East<br>Ardougne
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_176]
text=West<br>Ardougne
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_177]
text=Combat<br>Training<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_178]
text=Agility<br>Training<br>Area
colour=^white
mapfunction=no
category=1129

[mapelement_179]
text=Tree Gnome<br>Stronghold
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_180]
text=Grand Tree
colour=^white
mapfunction=no
category=1129

[mapelement_181]
text=Swamp
colour=^white
mapfunction=no
category=1129

[mapelement_182]
text=Gnome Ball<br>Field
colour=^white
mapfunction=no
category=1129

[mapelement_183]
text=Barbarian<br>Outpost
colour=^white
mapfunction=no
category=1129

[mapelement_184]
text=Underground<br>Pass
colour=^white
mapfunction=no
category=1129

[mapelement_185]
text=Battlefield
colour=^white
mapfunction=no
category=1129

[mapelement_186]
text=Baxtorian<br>Falls
colour=^white
mapfunction=no
category=1129

[mapelement_187]
text=Tree Gnome<br>Village
colour=^white
mapfunction=no
category=1129

[mapelement_188]
text=Fight<br>Arena
colour=^white
mapfunction=no
category=1129

[mapelement_189]
text=Port<br>Khazard
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_190]
text=Yanille
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_191]
text=Wizards'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_192]
text=Nightmare<br>Zone
colour=^white
mapfunction=no
category=1129

[mapelement_193]
text=Observatory
colour=^white
mapfunction=no
category=1129

[mapelement_194]
text=Necromancer
colour=^white
mapfunction=no
category=1129

[mapelement_195]
text=Gu'Tanoth
colour=^white
mapfunction=no
category=1129

[mapelement_196]
text=Feldip<br>Hills
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_197]
text=Ardougne<br>Zoo
colour=^white
mapfunction=no
category=1129

[mapelement_198]
text=Morytania
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_199]
text=Mort Myre<br>Swamp
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_200]
text=Canifis
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_201]
text=River<br>Salve
colour=^white
mapfunction=no
category=1129

[mapelement_202]
text=River Lum
colour=^white
mapfunction=no
category=1129

[mapelement_203]
text=Crombwick<br>Manor
colour=^white
mapfunction=no
category=1129

[mapelement_204]
text=Agility<br>Arena
colour=^white
mapfunction=no
category=1129

[mapelement_205]
text=Burthorpe
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_206]
text=Death<br>Plateau
colour=^white
mapfunction=no
category=1129

[mapelement_207]
text=Tirannwn
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_208]
text=Isafdar
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_209]
text=Arandar
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_210]
text=Prifddinas
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_211]
text=Tyras<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_212]
text=Iorwerth<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_213]
text=Trollheim
colour=^white
mapfunction=no
category=1129

[mapelement_214]
text=Troll<br>Stronghold
colour=^white
mapfunction=no
category=1129

[mapelement_215]
text=Mort'ton
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_216]
text=The<br>Hollows
colour=^white
mapfunction=no
category=1129

[mapelement_217]
text=Poison Waste
colour=^white
mapfunction=no
category=1129

[mapelement_218]
text=Castle Wars
colour=^white
mapfunction=no
category=1129

[mapelement_219]
text=Champions'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_220]
text=Rellekka
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_221]
text=Golden<br>Apple Tree
colour=^white
mapfunction=no
category=1129

[mapelement_222]
text=Lighthouse
colour=^white
mapfunction=no
category=1129

[mapelement_223]
text=Fremennik<br>Province
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_224]
text=Crafting<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_225]
text=Haunted<br>Woods
colour=^white
mapfunction=no
category=1129

[mapelement_226]
text=Miscellania
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_227]
text=Etceteria
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_228]
text=Ape Atoll
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_229]
text=Crash<br>Island
colour=^white
mapfunction=no
category=1129

[mapelement_230]
text=Marim
colour=^white
mapfunction=no
category=1129

[mapelement_231]
text=Fenkenstrain's<br>Castle
colour=^white
mapfunction=no
category=1129

[mapelement_232]
text=Mausoleum
colour=^white
mapfunction=no
category=1129

[mapelement_233]
text=Trollweiss<br>Mountain
colour=^white
mapfunction=no
category=1129

[mapelement_234]
text=Abandoned<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_235]
text=Ruins of<br>Uzer
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_236]
text=River<br>Elid
colour=^white
mapfunction=no
category=1129

[mapelement_237]
text=Kalphite<br>Lair
colour=^white
mapfunction=no
category=1129

[mapelement_238]
text=Pollnivneach
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_239]
text=Pyramid
colour=^white
mapfunction=no
category=1129

[mapelement_240]
text=Menaphos
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_241]
text=Sophanem
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_242]
text=Agility<br>Pyramid
colour=^white
mapfunction=no
category=1129

[mapelement_243]
text=Graveyard
colour=^white
mapfunction=no
category=1129

[mapelement_244]
text=Port<br>Phasmatys
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_245]
text=Ectofuntus
colour=^white
mapfunction=no
category=1129

[mapelement_246]
text=Mountain<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_247]
text=Kharidian<br>Desert
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_248]
text=Ice path
colour=^white
mapfunction=no
category=1129

[mapelement_249]
text=God Wars<br>Dungeon
colour=^white
mapfunction=no
category=1129

[mapelement_250]
text=Barrows
colour=^white
mapfunction=no
category=1129

[mapelement_251]
text=Jiggig
colour=^white
mapfunction=no
category=1129

[mapelement_252]
text=Mudskipper<br>Point
colour=^white
mapfunction=no
category=1129

[mapelement_253]
text=Nardah
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_254]
text=Mage<br>Training<br>Arena
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_255]
text=Keldagrim<br>Entrance
colour=^white
mapfunction=no
category=1129

[mapelement_256]
text=Waterbirth<br>Island
colour=^white
mapfunction=no
category=1129

[mapelement_257]
text=Lletya
colour=^white
mapfunction=no
category=1129

[mapelement_258]
text=Burgh de Rott
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_259]
text=Lizards
colour=^white
mapfunction=no
category=1129

[mapelement_260]
text=Quarry
colour=^white
mapfunction=no
category=1129

[mapelement_261]
text=Outpost
colour=^white
mapfunction=no
category=1129

[mapelement_262]
text=Mos Le'Harmless
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_263]
text=Distilleries
colour=^white
mapfunction=no
category=1129

[mapelement_264]
text=Ranging<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_265]
text=Dragontooth<br>Island
colour=^white
mapfunction=no
category=1129

[mapelement_266]
text=Piscatoris<br>Fishing<br>Colony
colour=^white
mapfunction=no
category=1129

[mapelement_267]
text=Here be<br>penguins
colour=^white
mapfunction=no
category=1129

[mapelement_268]
text=Void Knights'<br>Outpost
colour=^white
mapfunction=no
category=1129

[mapelement_269]
text=Lunar Isle
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_270]
text=Pirates' Cove
colour=^white
mapfunction=no
category=1129

[mapelement_271]
text=Vultures
colour=^white
mapfunction=no
category=1129

[mapelement_272]
text=Port<br>Tyras
colour=^white
mapfunction=no
category=1129

[mapelement_273]
text=Castle<br>Drakan
colour=^white
mapfunction=no
category=1129

[mapelement_274]
graphic="mapfunction,88"
vis=^mapelement_vis_both
category=1250

[mapelement_275]
text=Meiyerditch
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_276]
text=Witchaven
colour=^white
mapfunction=no
category=1129

[mapelement_277]
text=Warriors'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_278]
text=Musa Point
colour=^white
mapfunction=no
category=1129

[mapelement_279]
text=Eagles'<br>Peak
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_280]
text=Falconer
colour=^white
mapfunction=no
category=1129

[mapelement_281]
text=Barbarian<br>Assault
colour=^white
mapfunction=no
category=1129

[mapelement_282]
text=Iceberg
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_283]
text=Pest<br>Control
colour=^white
mapfunction=no
category=1129

[mapelement_284]
text=Neitiznot
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_285]
text=Jatizso
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_286]
text=Fremennik Isles
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_287]
text=Tower of<br>Life
colour=^white
mapfunction=no
category=1129

[mapelement_288]
text=Clocktower
colour=^white
mapfunction=no
category=1129

[mapelement_289]
text=Harmony
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_290]
text=Trawler
colour=^white
mapfunction=no
category=1129

[mapelement_291]
text=Otto's<br>Grotto
colour=^white
mapfunction=no
category=1129

[mapelement_292]
text=Clan Wars
colour=^white
mapfunction=no
category=1129

[mapelement_293]
text=Zul-Andra
colour=^white
mapfunction=no
category=1129

[mapelement_294]
text=Zulrah's<br>shrine
colour=^white
mapfunction=no
category=1129

[mapelement_295]
text=Silvarea
colour=^white
mapfunction=no
category=1129

[mapelement_296]
text=Kingdom of<br>Great Kourend
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_297]
text=Arceuus
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_298]
text=Hosidius
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_299]
text=Lovakengj
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_300]
text=Port<br>Piscarilius
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_301]
text=Shayzien
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_302]
text=Library
colour=^white
mapfunction=no
category=1129

[mapelement_303]
text=Dark<br>Altar
colour=^white
mapfunction=no
category=1129

[mapelement_304]
text=Sulphur<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_305]
text=Blast Mine
colour=^white
mapfunction=no
category=1129

[mapelement_306]
text=Lovakite<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_307]
text=Tower of<br>Magic
colour=^white
mapfunction=no
category=1129

[mapelement_308]
text=Mess
colour=^white
mapfunction=no
category=1129

[mapelement_309]
text=Saltpetre
colour=^white
mapfunction=no
category=1129

[mapelement_310]
text=Tithe Farm
colour=^white
mapfunction=no
category=1129

[mapelement_311]
text=Charcoal<br>Burners
colour=^white
mapfunction=no
category=1129

[mapelement_312]
text=Infirmary
colour=^white
mapfunction=no
category=1129

[mapelement_313]
text=Lizardman<br>Canyon
colour=^white
mapfunction=no
category=1129

[mapelement_314]
text=Combat<br>Ring
colour=^white
mapfunction=no
category=1129

[mapelement_315]
text=Graveyard of<br>Heroes
colour=^white
mapfunction=no
category=1129

[mapelement_316]
text=Shamans
colour=^white
mapfunction=no
category=1129

[mapelement_317]
text=Vinery
colour=^white
mapfunction=no
category=1129

[mapelement_318]
text=Woodcutting<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_319]
text=Doors of<br>Dinh
colour=^white
mapfunction=no
category=1129

[mapelement_320]
text=The<br>Wintertodt
colour=^white
mapfunction=no
category=1129

[mapelement_321]
text=Settlement<br>Ruins
colour=^white
mapfunction=no
category=1129

[mapelement_322]
text=Fishing Hamlet
colour=^white
mapfunction=no
category=1129

[mapelement_323]
text=Land's<br>End
colour=^white
mapfunction=no
category=1129

[mapelement_324]
text=Xeric's<br>Look out
colour=^white
mapfunction=no
category=1129

[mapelement_325]
text=Kourend<br>Woodland
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_326]
text=Unmarked<br>Grave
colour=^white
mapfunction=no
category=1129

[mapelement_327]
text=Crabclaw<br>Isle
colour=^white
mapfunction=no
category=1129

[mapelement_328]
text=Shayziens'<br>Wall
colour=^white
mapfunction=no
category=1129

[mapelement_329]
text=Lacerta<br>Falls
colour=^white
mapfunction=no
category=1129

[mapelement_330]
text=Xeric's<br>Shrine
colour=^white
mapfunction=no
category=1129

[mapelement_331]
text=Lizardman<br>Settlement
colour=^white
mapfunction=no
category=1129

[mapelement_332]
text=Mount<br>Quidamortem
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_333]
text=Chasm of Fire
colour=^white
mapfunction=no
category=1129

[mapelement_334]
text=Lower level
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_335]
text=Middle level
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_336]
text=Upper level
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_337]
text=Waterfiends
colour=^white
mapfunction=no
category=1129

[mapelement_338]
text=Mithril<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_339]
text=Brutal green<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_340]
text=Shadow<br>warriors
colour=^white
mapfunction=no
category=1129

[mapelement_341]
text=Pit scorpions
colour=^white
mapfunction=no
category=1129

[mapelement_342]
text=Hobgoblins
colour=^white
mapfunction=no
category=1129

[mapelement_343]
text=Ardougne<br>Sewers
colour=^white
mapfunction=no
category=1129

[mapelement_344]
text=Zombies & rocks
colour=^white
mapfunction=no
category=1129

[mapelement_345]
text=Rat Pits
colour=^white
mapfunction=no
category=1129

[mapelement_346]
text=Bats
colour=^white
mapfunction=no
category=1129

[mapelement_347]
text=Ogres
colour=^white
mapfunction=no
category=1129

[mapelement_348]
text=Dungeon<br>rats
colour=^white
mapfunction=no
category=1129

[mapelement_349]
text=Spiders
colour=^white
mapfunction=no
category=1129

[mapelement_350]
text=Here be<br>goblins
colour=^white
mapfunction=no
category=1129

[mapelement_351]
text=Skeletal wyverns
colour=^white
mapfunction=no
category=1129

[mapelement_352]
text=Pirates
colour=^white
mapfunction=no
category=1129

[mapelement_353]
text=Muggers
colour=^white
mapfunction=no
category=1129

[mapelement_354]
text=Ice warriors<br>& giants
colour=^white
mapfunction=no
category=1129

[mapelement_355]
text=Distillery
colour=^white
mapfunction=no
category=1129

[mapelement_356]
text=Dead people
colour=^white
mapfunction=no
category=1129

[mapelement_357]
text=Nothing<br>interesting<br>happens<br>here
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_358]
text=Agility course
colour=^white
mapfunction=no
category=1129

[mapelement_359]
text=Wire<br>machine
colour=^white
mapfunction=no
category=1129

[mapelement_360]
text=Bone<br>collector
colour=^white
mapfunction=no
category=1129

[mapelement_361]
text=Oldak's<br>teleportation<br>laboratory
colour=^white
mapfunction=no
category=1129

[mapelement_362]
text=Station
colour=^white
mapfunction=no
category=1129

[mapelement_363]
text=Council<br>chamber
colour=^white
mapfunction=no
category=1129

[mapelement_364]
text=Ur-tag
colour=^white
mapfunction=no
category=1129

[mapelement_365]
text=Ur-meg
colour=^white
mapfunction=no
category=1129

[mapelement_366]
text=Ur-zek & Ur-taal
colour=^white
mapfunction=no
category=1129

[mapelement_367]
text=Tegdak
colour=^white
mapfunction=no
category=1129

[mapelement_368]
text=Ur-vass
colour=^white
mapfunction=no
category=1129

[mapelement_369]
text=Nursery
colour=^white
mapfunction=no
category=1129

[mapelement_370]
text=Zanik's<br>bedroom
colour=^white
mapfunction=no
category=1129

[mapelement_371]
text=Beware of<br>the scorpions
colour=^white
mapfunction=no
category=1129

[mapelement_372]
text=Mining Guild
colour=^white
mapfunction=no
category=1129

[mapelement_373]
text=Access to<br>Falador
colour=^white
mapfunction=no
category=1129

[mapelement_374]
text=Hammerspike's<br>hangout
colour=^white
mapfunction=no
category=1129

[mapelement_375]
text=Boot
colour=^white
mapfunction=no
category=1129

[mapelement_376]
text=Kurask
colour=^white
mapfunction=no
category=1129

[mapelement_377]
text=Cave crawlers
colour=^white
mapfunction=no
category=1129

[mapelement_378]
text=Turoth
colour=^white
mapfunction=no
category=1129

[mapelement_379]
text=Basilisks
colour=^white
mapfunction=no
category=1129

[mapelement_380]
text=Rock<br>slugs
colour=^white
mapfunction=no
category=1129

[mapelement_381]
text=Cockatrice
colour=^white
mapfunction=no
category=1129

[mapelement_382]
text=Pyrefiends
colour=^white
mapfunction=no
category=1129

[mapelement_383]
text=Jellies
colour=^white
mapfunction=no
category=1129

[mapelement_384]
text=Saradomin's<br>Encampment
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_385]
text=Zamorak's<br>Fortress
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_386]
text=Armadyl's<br>Eyrie
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_387]
text=Bandos's<br>Stronghold
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_388]
text=Queen's<br>Chamber
colour=^white
mapfunction=no
category=1129

[mapelement_389]
text=Soldiers
colour=^white
mapfunction=no
category=1129

[mapelement_390]
text=Guardians
colour=^white
mapfunction=no
category=1129

[mapelement_391]
text=Moss giants
colour=^white
mapfunction=no
category=1129

[mapelement_392]
text=Dogs
colour=^white
mapfunction=no
category=1129

[mapelement_393]
text=Fire<br>giants
colour=^white
mapfunction=no
category=1129

[mapelement_394]
text=Red dragons
colour=^white
mapfunction=no
category=1129

[mapelement_395]
text=Bronze<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_396]
text=Iron & steel<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_397]
text="Bronze, iron &<br>steel dragons"
colour=^white
mapfunction=no
category=1129

[mapelement_398]
text=Greater demons
colour=^white
mapfunction=no
category=1129

[mapelement_399]
text=Jogres
colour=^white
mapfunction=no
category=1129

[mapelement_400]
text=Elvarg
colour=^white
mapfunction=no
category=1129

[mapelement_401]
text=Lesser demons
colour=^white
mapfunction=no
category=1129

[mapelement_402]
text=Baby green<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_403]
text=Black demons
colour=^white
mapfunction=no
category=1129

[mapelement_404]
text=Black<br>demons
colour=^white
mapfunction=no
category=1129

[mapelement_405]
text=Red Spiders
colour=^white
mapfunction=no
category=1129

[mapelement_406]
text=Skeletons
colour=^white
mapfunction=no
category=1129

[mapelement_407]
text=River Kelda
colour=^white
mapfunction=no
category=1129

[mapelement_408]
text=Dondakan's<br>rock
colour=^white
mapfunction=no
category=1129

[mapelement_409]
text=Minecarts
colour=^white
mapfunction=no
category=1129

[mapelement_410]
text=Blast<br>Furnace
colour=^white
mapfunction=no
category=1129

[mapelement_411]
text=Brewery
colour=^white
mapfunction=no
category=1129

[mapelement_412]
text=Black<br>Guard<br>H.Q.
colour=^white
mapfunction=no
category=1129

[mapelement_413]
text=Trolls
colour=^white
mapfunction=no
category=1129

[mapelement_414]
text=Exit
colour=^white
mapfunction=no
category=1129

[mapelement_415]
text=Terror dogs
colour=^white
mapfunction=no
category=1129

[mapelement_416]
text=Essence<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_417]
text=Miscellania<br>Expansion
colour=^white
mapfunction=no
category=1129

[mapelement_418]
text=Sea snakes
colour=^white
mapfunction=no
category=1129

[mapelement_419]
text=H.A.M. Cult
colour=^white
mapfunction=no
category=1129

[mapelement_420]
text=Draynor Sewers
colour=^white
mapfunction=no
category=1129

[mapelement_421]
text=Mine
colour=^white
mapfunction=no
category=1129

[mapelement_422]
text=Watermill<br>cellar
colour=^white
mapfunction=no
category=1129

[mapelement_423]
text=Champions'<br>Challenge
colour=^white
mapfunction=no
category=1129

[mapelement_424]
text=Draynor Manor<br>basement
colour=^white
mapfunction=no
category=1129

[mapelement_425]
text=VTAM Corporation
colour=^white
mapfunction=no
category=1129

[mapelement_426]
text=Bank vault
colour=^white
mapfunction=no
category=1129

[mapelement_427]
text=Goblin Maze
colour=^white
mapfunction=no
category=1129

[mapelement_428]
text=Chasm of<br>Tears
colour=^white
mapfunction=no
category=1129

[mapelement_429]
text=Tears of<br>Guthix
colour=^white
mapfunction=no
category=1129

[mapelement_430]
text=Lumbridge<br>Castle<br>cellar
colour=^white
mapfunction=no
category=1129

[mapelement_431]
text=Giant frogs
colour=^white
mapfunction=no
category=1129

[mapelement_432]
text=Hill giants
colour=^white
mapfunction=no
category=1129

[mapelement_433]
text=Chronozon
colour=^white
mapfunction=no
category=1129

[mapelement_434]
text=Here be<br>dead stuff
colour=^white
mapfunction=no
category=1129

[mapelement_435]
text=Thugs
colour=^white
mapfunction=no
category=1129

[mapelement_436]
text=Dave's<br>Basement<br>of Doom
colour=^white
mapfunction=no
category=1129

[mapelement_437]
text=Poison spiders
colour=^white
mapfunction=no
category=1129

[mapelement_438]
text=Poison<br>spiders
colour=^white
mapfunction=no
category=1129

[mapelement_439]
text=Zombies
colour=^white
mapfunction=no
category=1129

[mapelement_440]
text=Skeletons<br>& zombies
colour=^white
mapfunction=no
category=1129

[mapelement_441]
text=Earth warriors
colour=^white
mapfunction=no
category=1129

[mapelement_442]
text=Chaos<br>druids
colour=^white
mapfunction=no
category=1129

[mapelement_443]
text=Rats
colour=^white
mapfunction=no
category=1129

[mapelement_444]
text=Here be a<br>big mole
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_445]
text=Motherlode Mine
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_446]
text=Obstacle<br>course
colour=^white
mapfunction=no
category=1129

[mapelement_447]
text=Skullball
colour=^white
mapfunction=no
category=1129

[mapelement_448]
text=Shades
colour=^white
mapfunction=no
category=1129

[mapelement_449]
text=Here be odd stuff
colour=^white
mapfunction=no
category=1129

[mapelement_450]
text=Nechryael
colour=^white
mapfunction=no
category=1129

[mapelement_451]
text=Abyssal<br>demons
colour=^white
mapfunction=no
category=1129

[mapelement_452]
text=Bloodvelds
colour=^white
mapfunction=no
category=1129

[mapelement_453]
text=Gargoyles
colour=^white
mapfunction=no
category=1129

[mapelement_454]
text=Aberrant<br>Spectres
colour=^white
mapfunction=no
category=1129

[mapelement_455]
text=Ankou
colour=^white
mapfunction=no
category=1129

[mapelement_456]
text=Cave horrors<br>&<br>albino bats
colour=^white
mapfunction=no
category=1129

[mapelement_457]
text=Altar
colour=^white
mapfunction=no
category=1129

[mapelement_458]
text=Lizards &<br>Zamorak fighters
colour=^white
mapfunction=no
category=1129

[mapelement_459]
text=War
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_460]
text=Gift of<br>Peace
colour=^white
mapfunction=no
category=1129

[mapelement_461]
text=Famine
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_462]
text=Grain of<br>Plenty
colour=^white
mapfunction=no
category=1129

[mapelement_463]
text=Pestilence
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_464]
text=Box of<br>Health
colour=^white
mapfunction=no
category=1129

[mapelement_465]
text=Death
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_466]
text=Cradle of<br>Life
colour=^white
mapfunction=no
category=1129

[mapelement_467]
text=Cauldron of<br>Thunder
colour=^white
mapfunction=no
category=1129

[mapelement_468]
text=Black Knights'<br>Base
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_469]
text=Hellhounds
colour=^white
mapfunction=no
category=1129

[mapelement_470]
text=Fire Obelisk
colour=^white
mapfunction=no
category=1129

[mapelement_471]
text=Black dragons
colour=^white
mapfunction=no
category=1129

[mapelement_472]
text=Black<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_473]
text=Dramen Tree
colour=^white
mapfunction=no
category=1129

[mapelement_474]
text=Animated<br>axes
colour=^white
mapfunction=no
category=1129

[mapelement_475]
text=Chaos<br>dwarves
colour=^white
mapfunction=no
category=1129

[mapelement_476]
text=Blue<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_477]
text=Poisonous<br>scorpions
colour=^white
mapfunction=no
category=1129

[mapelement_478]
text=Cyclopes
colour=^white
mapfunction=no
category=1129

[mapelement_479]
text=Cyclopes<br>& Axes
colour=^white
mapfunction=no
category=1129

[mapelement_480]
text=Ice Queen's<br>Lair
colour=^white
mapfunction=no
category=1129

[mapelement_481]
text=Fountain<br>of Heroes
colour=^white
mapfunction=no
category=1129

[mapelement_482]
text=Mountain<br>dwarves
colour=^white
mapfunction=no
category=1129

[mapelement_483]
text=Nora T. Hagg's<br>cellar
colour=^white
mapfunction=no
category=1129

[mapelement_484]
text=Key Master
colour=^white
mapfunction=no
category=1129

[mapelement_485]
text=Beware of<br>the dog
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_486]
text=Anger
colour=^white
mapfunction=no
category=1129

[mapelement_487]
text=Hopelessness
colour=^white
mapfunction=no
category=1129

[mapelement_488]
text=Confusion
colour=^white
mapfunction=no
category=1129

[mapelement_489]
text=Fear
colour=^white
mapfunction=no
category=1129

[mapelement_490]
text=Goutweed<br>store
colour=^white
mapfunction=no
category=1129

[mapelement_491]
text=Troll<br>generals
colour=^white
mapfunction=no
category=1129

[mapelement_492]
text=Burntmeat's<br>Kitchen
colour=^white
mapfunction=no
category=1129

[mapelement_493]
text=Fight Pit
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_494]
text=Fight Cave
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_495]
text=Sub-level 1
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_496]
text=Sub-level 2
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_497]
text=Sub-level 3
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_498]
text=Sub-level 4
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_499]
text=Sub-level 5
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_500]
text=Sub-level 6
colour=^yellow
size=1
mapfunction=no
category=1129

[mapelement_501]
text=Dagannoth
colour=^white
mapfunction=no
category=1129

[mapelement_502]
text=Giant rock crabs
colour=^white
mapfunction=no
category=1129

[mapelement_503]
text=Giant<br>rock crabs
colour=^white
mapfunction=no
category=1129

[mapelement_504]
text=Rock lobsters
colour=^white
mapfunction=no
category=1129

[mapelement_505]
text=Rock<br>lobsters
colour=^white
mapfunction=no
category=1129

[mapelement_506]
text=Wallasalki
colour=^white
mapfunction=no
category=1129

[mapelement_507]
text=Dagannoth Kings
colour=^white
mapfunction=no
category=1129

[mapelement_508]
text=Shadow<br>spiders
colour=^white
mapfunction=no
category=1129

[mapelement_509]
text=Agility<br>course<br>spikes
colour=^white
mapfunction=no
category=1129

[mapelement_510]
text=Mage Arena<br>bank
colour=^white
mapfunction=no
category=1129

[mapelement_511]
text=King<br>Black<br>Dragon
colour=^white
mapfunction=no
category=1129

[mapelement_512]
text=Corporeal<br>Beast
colour=^white
mapfunction=no
category=1129

[mapelement_513]
text=Salarin the<br>Twisted
colour=^white
mapfunction=no
category=1129

[mapelement_514]
text=Smoke devils
colour=^white
mapfunction=no
category=1129

[mapelement_515]
text=Thermonuclear<br>Smoke Devil
colour=^white
mapfunction=no
category=1129

[mapelement_516]
text=Throne room
colour=^white
mapfunction=no
category=1129

[mapelement_517]
text=Beware of the<br>mushrooms
colour=^white
mapfunction=no
category=1129

[mapelement_518]
text=Shrine
colour=^white
mapfunction=no
category=1129

[mapelement_519]
text=Otherworldly<br>beings
colour=^white
mapfunction=no
category=1129

[mapelement_520]
text=Puro-puro
colour=^white
mapfunction=no
category=1129

[mapelement_521]
text=Tanglefeet
colour=^white
mapfunction=no
category=1129

[mapelement_522]
text=Brimstail
colour=^white
mapfunction=no
category=1129

[mapelement_523]
text=Voice of Yama
colour=^white
mapfunction=no
category=1129

[mapelement_524]
text=Ents
colour=^white
mapfunction=no
category=1129

[mapelement_525]
text="Brutal black, blue<br>& red dragons"
colour=^white
mapfunction=no
category=1129

[mapelement_526]
text=Bronze & iron<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_527]
text=Steel<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_528]
text=Dark<br>beasts
colour=^white
mapfunction=no
category=1129

[mapelement_529]
text=Ghosts
colour=^white
mapfunction=no
category=1129

[mapelement_530]
text=Dust devils
colour=^white
mapfunction=no
category=1129

[mapelement_531]
text=Sand<br>crabs
colour=^white
mapfunction=no
category=1129

[mapelement_532]
text=Spectres
colour=^white
mapfunction=no
category=1129

[mapelement_533]
text=Banshees
colour=^white
mapfunction=no
category=1129

[mapelement_534]
text=Mor Ul Rek
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_535]
text=The Inferno
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_536]
text=Lizardman<br>Caves
colour=^white
mapfunction=no
category=1129

[mapelement_537]
text=Underwater
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_538]
text=Wyverns
colour=^white
mapfunction=no
category=1129

[mapelement_539]
text=Wyverns<br>Task Only
colour=^white
mapfunction=no
category=1129

[mapelement_540]
text=Volcano Mine
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_541]
text=A
colour=^white
vis=^mapelement_vis_both
mapfunction=no
category=1129

[mapelement_542]
text=B
colour=^white
vis=^mapelement_vis_both
mapfunction=no
category=1129

[mapelement_543]
text=C
colour=^white
vis=^mapelement_vis_both
mapfunction=no
category=1129

[mapelement_544]
text=Fossil<br>Island
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_545]
text=Museum<br>Camp
colour=^white
mapfunction=no
category=1129

[mapelement_546]
text=The Warrens
colour=^white
mapfunction=no
category=1129

[mapelement_547]
text=Mushroom<br>Forest
colour=^white
mapfunction=no
category=1129

[mapelement_548]
text=House<br>on the<br>Hill
colour=^white
mapfunction=no
category=1129

[mapelement_549]
text=Volcano
colour=^white
mapfunction=no
category=1129

[mapelement_550]
text=Tar<br>Swamp
colour=^white
mapfunction=no
category=1129

[mapelement_551]
text=Crabclaw Caves
colour=^white
mapfunction=no
category=1129

[mapelement_552]
text=Wilderness<br>Emblem Trader
colour=^white
mapfunction=no
category=1129

[mapelement_553]
text=Ice giants
colour=^white
mapfunction=no
category=1129

[mapelement_554]
text=Greater<br>demons
colour=^white
mapfunction=no
category=1129

[mapelement_555]
text=Green dragons
colour=^white
mapfunction=no
category=1129

[mapelement_556]
text=Green<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_557]
text=Revenants
colour=^white
mapfunction=no
category=1129

[mapelement_558]
text=Myths'<br>Guild
colour=^white
mapfunction=no
category=1129

[mapelement_559]
text=Corsair<br>Cove
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_560]
text=Ancient<br>Forge
colour=^white
mapfunction=no
category=1129

[mapelement_561]
text=Ogresses
colour=^white
mapfunction=no
category=1129

[mapelement_562]
text=Chinchompas
colour=^white
mapfunction=no
category=1129

[mapelement_563]
text=Dragons
colour=^white
mapfunction=no
category=1129

[mapelement_564]
text=Baby dragons
colour=^white
mapfunction=no
category=1129

[mapelement_565]
text=Chapel
colour=^white
mapfunction=no
category=1129

[mapelement_566]
text=Ungael
colour=^white
mapfunction=no
category=1129

[mapelement_567]
text=Lithkren
colour=^white
mapfunction=no
category=1129

[mapelement_568]
text=War Tent
colour=^white
mapfunction=no
category=1129

[mapelement_569]
text=Foodhall
colour=^white
mapfunction=no
category=1129

[mapelement_570]
text=Kourend<br>Castle
colour=^white
mapfunction=no
category=1129

[mapelement_571]
text=Kebos<br>Lowlands
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_572]
text=Paterdomus<br>Temple
colour=^white
mapfunction=no
category=1129

[mapelement_573]
text=Darkmeyer
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_574]
text=Slepe
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_575]
text=Ver Sinhaza
colour=^white
mapfunction=no
category=1129

[mapelement_576]
graphic="mapfunction,89"
vis=^mapelement_vis_both
category=1251

[mapelement_577]
graphic="mapfunction,90"
vis=^mapelement_vis_both
category=1252

[mapelement_578]
graphic="mapfunction,91"
vis=^mapelement_vis_both
category=1253

[mapelement_579]
graphic="mapfunction,92"
vis=^mapelement_vis_both
category=1254

[mapelement_580]
graphic="mapfunction,93"
vis=^mapelement_vis_both
category=1255

[mapelement_581]
graphic="mapfunction,94"
vis=^mapelement_vis_both
category=1256

[mapelement_582]
graphic="mapfunction,95"
vis=^mapelement_vis_both
category=1257

[mapelement_583]
graphic="mapfunction,96"
vis=^mapelement_vis_both
category=1258

[mapelement_584]
graphic="mapfunction,97"
vis=^mapelement_vis_both
category=1259

[mapelement_585]
graphic="mapfunction,98"
vis=^mapelement_vis_both
category=1260

[mapelement_586]
graphic="mapfunction,99"
vis=^mapelement_vis_both
category=1261

[mapelement_587]
graphic="mapfunction,100"
vis=^mapelement_vis_both
category=1262

[mapelement_588]
graphic="mapfunction,101"
vis=^mapelement_vis_both
category=1263

[mapelement_589]
graphic="mapfunction,103"
vis=^mapelement_vis_both
category=1264

[mapelement_590]
graphic="mapfunction,115"
vis=^mapelement_vis_both
category=1265

[mapelement_591]
graphic="mapfunction,106"
vis=^mapelement_vis_both
category=1266

[mapelement_592]
graphic="mapfunction,107"
vis=^mapelement_vis_both
category=1267

[mapelement_593]
graphic="mapfunction,108"
vis=^mapelement_vis_both
category=1268

[mapelement_594]
graphic="mapfunction,110"
vis=^mapelement_vis_both
category=1269

[mapelement_595]
graphic="mapfunction,111"
vis=^mapelement_vis_both
category=1270

[mapelement_596]
graphic="mapfunction,112"
vis=^mapelement_vis_both
category=1271

[mapelement_597]
graphic="mapfunction,113"
vis=^mapelement_vis_both
category=1272

[mapelement_598]
graphic="mapfunction,114"
vis=^mapelement_vis_both
category=1273

[mapelement_599]
graphic="mapfunction,116"
vis=^mapelement_vis_both
category=1274

[mapelement_600]
graphic="mapfunction,117"
vis=^mapelement_vis_both
category=1275

[mapelement_601]
text=Kalphite<br>Cave
colour=^white
mapfunction=no
category=1129

[mapelement_602]
text=Lovakengj<br>Assembly
colour=^white
mapfunction=no
category=1129

[mapelement_603]
text=The Forsaken<br>Tower
colour=^white
mapfunction=no
category=1129

[mapelement_604]
text=Mount<br>Karuulm
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_605]
text=Farming Guild
colour=^white
mapfunction=no
category=1129

[mapelement_606]
text=Battlefront
colour=^white
mapfunction=no
category=1129

[mapelement_607]
text=Molch
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_608]
text=Kebos Swamp
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_609]
text=Lake Molch
colour=^white
mapfunction=no
category=1129

[mapelement_610]
text=River Molch
colour=^white
mapfunction=no
category=1129

[mapelement_611]
text=Wyrms
colour=^white
mapfunction=no
category=1129

[mapelement_612]
text=Drakes
colour=^white
mapfunction=no
category=1129

[mapelement_613]
text=Hydras
colour=^white
mapfunction=no
category=1129

[mapelement_614]
text=Alchemical<br>Hydra
colour=^white
mapfunction=no
category=1129

[mapelement_615]
text=Sulphur<br>lizards
colour=^white
mapfunction=no
category=1129

[mapelement_616]
text=Tasakaal
colour=^white
mapfunction=no
category=1129

[mapelement_617]
text=Hespori
colour=^white
mapfunction=no
category=1129

[mapelement_618]
text=Lizardman<br>Temple
colour=^white
mapfunction=no
category=1129

[mapelement_619]
graphic="mapfunction,118"
vis=^mapelement_vis_both
category=1317

[mapelement_620]
text=Forthos Ruin
colour=^white
mapfunction=no
category=1129

[mapelement_621]
text=Kingstown
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_622]
text=Wine of<br>Zamorak
colour=^white
mapfunction=no
category=1129

[mapelement_623]
text=Larran's<br>Chest
colour=^white
mapfunction=no
category=1129

[mapelement_624]
text=River<br>Dougne
colour=^white
mapfunction=no
category=1129

[mapelement_625]
text=River<br>Hos
colour=^white
mapfunction=no
category=1129

[mapelement_626]
text=Undead<br>druids
colour=^white
mapfunction=no
category=1129

[mapelement_627]
text=Bone<br>Burner
colour=^white
mapfunction=no
category=1129

[mapelement_628]
text=Temple Spiders
colour=^white
mapfunction=no
category=1129

[mapelement_629]
text=Sarachnis
colour=^white
mapfunction=no
category=1129

[mapelement_630]
graphic="mapfunction,109"
vis=^mapelement_vis_both
category=1070

[mapelement_631]
graphic="mapfunction,119"
vis=^mapelement_vis_both
category=1396

[mapelement_632]
text=Moss<br>giants
colour=^white
mapfunction=no
category=1129

[mapelement_633]
text=Trahaearn<br>Mine
colour=^white
mapfunction=no
category=1129

[mapelement_634]
text=Zalcano
colour=^white
mapfunction=no
category=1129

[mapelement_635]
text=The Gauntlet
colour=^white
mapfunction=no
category=1129

[mapelement_636]
text=Gwenith
colour=^white
mapfunction=no
category=1129

[mapelement_637]
text=Last Man<br>Standing
colour=^white
mapfunction=no
category=1129

[mapelement_638]
text=The Mountain
colour=^white
mapfunction=no
category=1129

[mapelement_639]
text=Trinity<br>Outpost
colour=^white
mapfunction=no
category=1129

[mapelement_640]
text=Debtor<br>Hideout
colour=^white
mapfunction=no
category=1129

[mapelement_641]
text=Moser<br>Settlement
colour=^white
mapfunction=no
category=1129

[mapelement_642]
text=Rocky<br>Outcrop
colour=^white
mapfunction=no
category=1129

[mapelement_643]
text=Island<br>of Stone
colour=^white
mapfunction=no
category=1129

[mapelement_644]
text=Basilisk<br>Knights
colour=^white
mapfunction=no
category=1129

[mapelement_645]
graphic="mapfunction,123"
vis=^mapelement_vis_both
category=176

[mapelement_646]
text=Lesser<br>demons
colour=^white
mapfunction=no
category=1129

[mapelement_647]
text=The<br>Nightmare
colour=^white
mapfunction=no
category=1129

[mapelement_648]
text=Shura
colour=^white
mapfunction=no
category=1129

[mapelement_649]
text=Elves
colour=^white
mapfunction=no
category=1129

[mapelement_650]
graphic="mapfunction,124"
vis=^mapelement_vis_both
category=1425

[mapelement_651]
text=Icyene<br>Graveyard
colour=^white
mapfunction=no
category=1129

[mapelement_652]
graphic="mapfunction,125"
vis=^mapelement_vis_both
category=1459

[mapelement_653]
text=Crypt
colour=^white
mapfunction=no
category=1129

[mapelement_654]
text=Ferox<br>Enclave
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_655]
text=Citharede<br>Abbey
colour=^white
mapfunction=no
category=1129

[mapelement_656]
text=South Falador<br>Farm
colour=^white
mapfunction=no
category=1129

[mapelement_657]
text=Sourhog Cave
colour=^white
mapfunction=no
category=1129

[mapelement_658]
text=Isle of Souls
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_659]
text=Soul Wars<br>Arena
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_660]
text=Soul Wars<br>Lobby
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_661]
text=Soul<br>Obelisk
colour=^white
mapfunction=no
category=1129

[mapelement_662]
text=Western<br>Graveyard
colour=^white
mapfunction=no
category=1129

[mapelement_663]
text=Eastern<br>Graveyard
colour=^white
mapfunction=no
category=1129

[mapelement_664]
text=Blue<br>Base
colour=^white
mapfunction=no
category=1129

[mapelement_665]
text=Red<br>Base
colour=^white
mapfunction=no
category=1129

[mapelement_666]
text=Avatar of<br>Creation
colour=^white
mapfunction=no
category=1129

[mapelement_667]
text=Avatar of<br>Destruction
colour=^white
mapfunction=no
category=1129

[mapelement_668]
text=Iron<br>dragons
colour=^white
mapfunction=no
category=1129

[mapelement_669]
text=Desert Island
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_670]
text=Wild Varrock
colour=0xff981f
size=2
mapfunction=no
category=1129

[mapelement_671]
text=Hut
colour=^white
mapfunction=no
category=1129

[mapelement_672]
text=Stone Circle
colour=^white
mapfunction=no
category=1129

[mapelement_673]
text=Court of Chaos
colour=^white
mapfunction=no
category=1129

[mapelement_674]
text=Old Manor
colour=^white
mapfunction=no
category=1129

[mapelement_675]
text=Town Center
colour=^white
mapfunction=no
category=1129

[mapelement_676]
text=Blank Tower
colour=^white
mapfunction=no
category=1129

[mapelement_677]
text=Trading Post
colour=^white
mapfunction=no
category=1129

[mapelement_678]
text=Dark Warrior's<br>Palace
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_679]
text=Pillars of Sacrifice
colour=^white
mapfunction=no
category=1129

[mapelement_680]
graphic="mapfunction,126"
vis=^mapelement_vis_both
category=1499

[mapelement_681]
text=Ruins of<br>Unkah
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_682]
text=Sea Spirit<br>Dock
colour=^white
mapfunction=no
category=1129

[mapelement_683]
text=Tempoross<br>Cove
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_684]
text=Camdozaal<br>Vault
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_685]
text=Ramarno
colour=^white
mapfunction=no
category=1129

[mapelement_686]
text=Offering<br>Altar
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_687]
text=Golem<br>Workshop
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_688]
text=Camdozaal<br>Mines
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_689]
text=Clan Hub
colour=^white
mapfunction=no
category=1129

[mapelement_690]
graphic="mapfunction,127"
vis=^mapelement_vis_both
category=1551

[mapelement_691]
text=Shayzien<br>Encampment
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_692]
text=Giant<br>Pit
colour=^white
mapfunction=no
category=1129

[mapelement_693]
text=Ruins<br>of Morra
colour=^white
mapfunction=no
category=1129

[mapelement_694]
text=Shayzia<br>Ruin
colour=^white
mapfunction=no
category=1129

[mapelement_695]
text=Northern<br>Tundras
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_696]
text=River<br>of Souls
colour=^white
mapfunction=no
category=1129

[mapelement_697]
graphic="mapfunction,128"
vis=^mapelement_vis_both
category=1579

[mapelement_698]
text=Sire
colour=^white
mapfunction=no
category=1129

[mapelement_699]
text=Here be<br>spiders
colour=^white
mapfunction=no
category=1129

[mapelement_700]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_701]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_702]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_703]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_704]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_705]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_706]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_707]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_708]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_709]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_710]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_711]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_712]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_713]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_714]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_715]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_716]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_717]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_718]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_719]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_720]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_721]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_722]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_723]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_724]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_725]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_726]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_727]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_728]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_729]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_730]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_731]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_732]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_733]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_734]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_735]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_736]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_737]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_738]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_739]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_740]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_741]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_742]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_743]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_744]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_745]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_746]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_747]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_748]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_749]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_750]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_751]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_752]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_753]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_754]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_755]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_756]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_757]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_758]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_759]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_760]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_761]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_762]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_763]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_764]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_765]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_766]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_767]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_768]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_769]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_770]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_771]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_772]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_773]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_774]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_775]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_776]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_777]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_778]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_779]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_780]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_781]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_782]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_783]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_784]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_785]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_786]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_787]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_788]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_789]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_790]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_791]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_792]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_793]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_794]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_795]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_796]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_797]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_798]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_799]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_800]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_801]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_802]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_803]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_804]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_805]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_806]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_807]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_808]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_809]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_810]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_811]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_812]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_813]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_814]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_815]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_816]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_817]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_818]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_819]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_820]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_821]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_822]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_823]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_824]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_825]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_826]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_827]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_828]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_829]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_830]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_831]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_832]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_833]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_834]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_835]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_836]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_837]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_838]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_839]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_840]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_841]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_842]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_843]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_844]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_845]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_846]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_847]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_848]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_849]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_850]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_851]
text=Ancient<br>Prison
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_852]
text=Greater<br>nechryael
colour=^white
mapfunction=no
category=1129

[mapelement_853]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_854]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

[mapelement_855]
text=Ruins of<br>Ullek
colour=^white
size=1
mapfunction=no
category=1129

[mapelement_856]
text=Necropolis
colour=^white
mapfunction=no
category=1129

[mapelement_857]
graphic="mapfunction,6"
vis=^mapelement_vis_both
category=1056

